# Generated by Django 5.2.8 on 2025-11-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=100)),
                ('Complete', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
