# Generated by Django 5.2.8 on 2025-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Publish_date', models.DateField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
